server:
 port: 9004

eureka:
 client:
  service-url:
   defaultZone: http://localhost:9001/eureka/
   
spring:
 application:
  name: api-gateway
 profiles:
  active: dev
  
 security:
  oauth2:
   client:
    registration:
     gateway:
      client-id: bank-client
      client-secret: secret
      authorization-grant-type: client_credentials
      scope: internal
      provider: auth-server
    provider:
     auth-server:
      token-uri: http://auth-service/Auth/oauth/token

   resourceserver:
    jwt:
     issuer-uri: http://auth-service/Auth