---------------------Create Customer Identification Numebr
1. -> Alphabet Prefix Function And Trigger Function to Build Customer ID

CREATE OR REPLACE FUNCTION Generate_CIF_No()
RETURNS TRIGGER AS $$
DECLARE
    seq_val BIGINT;
    n BIGINT;
    prefix TEXT  := 'AAAA';
    i INT;
    char_index INT;
    suffix BIGINT;
BEGIN
    -- seq_val is the identity id (already generated by DB on insert)
    seq_val := NEW.Customer_Id;
	
	
	-- Special case: if name is ADMIN USER or SUPER USER
    IF UPPER(NEW.first_name) = 'ADMIN' OR UPPER(NEW.first_name) = 'SUPER' THEN
        prefix := UPPER(NEW.first_name);
    ELSE
    -- Generate alphabet prefix (4 letters)
		n := seq_val - 1; -- zero-based for letters
		FOR i IN REVERSE 1..4 LOOP
			char_index := (n % 26);
			prefix := overlay(prefix placing chr(65 + char_index) from i for 1);
			n := n / 26;
		END LOOP;
	END IF;

    -- Numeric suffix starts at 001001
    suffix := seq_val + 1000;

    -- Assign business key
    NEW.CIF_NO := prefix || lpad(suffix::TEXT, 6, '0');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;



--2. Trigger on Table

CREATE TRIGGER CIF_No_Trigger
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
WHEN (NEW.CIF_NO IS NULL)
EXECUTE FUNCTION Generate_CIF_No();

------------Prevents CIF_NO Update
1. -> Use a BEFORE UPDATE trigger

CREATE OR REPLACE FUNCTION Prevent_CIF_No()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.CIF_NO IS DISTINCT FROM OLD.CIF_NO THEN
        RAISE EXCEPTION 'CIF_NO cannot be updated once set';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--2. Create Trigger on Table 
CREATE TRIGGER Prevent_CIF_No_Trigger
BEFORE UPDATE OF CIF_NO ON CUSTOMER
FOR EACH ROW
EXECUTE FUNCTION Prevent_CIF_No();

----------For Branch Code Generate--------------

CREATE OR REPLACE FUNCTION Prevent_Branch_Code()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.Branch_Code IS DISTINCT FROM OLD.Branch_Code THEN
        RAISE EXCEPTION 'Branch_Code cannot be updated once generated.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER Prevent_Branch_Code_Trigger
BEFORE UPDATE ON BRANCH
FOR EACH ROW
EXECUTE FUNCTION Prevent_Branch_Code();


----------For Account Number--------------

CREATE OR REPLACE FUNCTION Prevent_Account_No()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.Account_Number IS DISTINCT FROM OLD.Account_Number THEN
        RAISE EXCEPTION 'Account_Number cannot be updated once generated.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER Prevent_Account_No_Trigger
BEFORE UPDATE ON ACCOUNT
FOR EACH ROW
EXECUTE FUNCTION Prevent_Account_No();
