spring:
 datasource:
#  url: jdbc:postgresql://ep-empty-surf-adsq0sfw-pooler.c-2.us-east-1.aws.neon.tech:5432/bank-app-db?sslmode=require
#  username: neondb_owner
#  password: npg_w5UGmkIbOg8A
  url: jdbc:postgresql://localhost:5432/bankdb
  username: bankapp
  password: LexisNexis@2025
  driver-class-name: org.postgresql.Driver
  hikari:
   minimum-idle: 5
   maximum-pool-size: 20
   idle-timeout: 30000
   pool-name: NeonHikariCP
   maxLifetime: 1800000
   connectionTimeout: 20000
   transaction-isolation: TRANSACTION_READ_COMMITTED
# ===============================
# JPA / HIBERNATE
# ===============================
 jpa:
  database: default
  hibernate:
   ddl-auto: none
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true 
# ===============================
# RabbitMQ Listener
# ===============================   
 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 

account:
 service:
  url: http://localhost:9006/Account  # Example: URL of account-service   

  
 