spring:
 application:
  name: api-gateway
 
 main:
  web-application-type: reactive

 security:
   oauth2:
    client:
     registration:
      gateway:
       client-id: bank-client
       client-secret: secret
       authorization-grant-type: client_credentials
       scope: internal
       provider: auth-server
     provider:
      auth-server:
       token-uri: http://auth-service/Auth/oauth/token
   resourceserver:
    jwt:
     issuer-uri: http://auth-service/Auth  
      
 cloud:
  config:
   profile: dev
  gateway:
   default-filters:
    - TokenRelay
   server:
    webflux:
     routes:
      - id: user-service
        uri: lb://USER-MANAGEMENT-SERVICE
        predicates:
         - Path=/User/**
      - id: bank-config-service
        uri: lb://BANK-CONFIG-SERVICE
        predicates:
         - Path=/config/**
      - id: customer-service
        uri: lb://CUSTOMER-SERVICE
        predicates:
         - Path=/Customer/**
      - id: account-service
        uri: lb://ACCOUNT-SERVICE
        predicates:
         - Path=/Account/**
      - id: transaction-service
        uri: lb://TRANSACTION-SERVICE
        predicates:
         - Path=/Transaction/**
      - id: loan-service
        uri: lb://LOAN-SERVICE
        predicates:
         - Path=/Loan/**
      - id: fraud-detection-service
        uri: lb://FRAUD-DETECTION-SERVICE
        predicates:
         - Path=/Fraud-detect/**
      - id: notification-service
        uri: lb://NOTIFIATION-SERVICE
        predicates:
         - Path=/Notification/**

    
 
# ===============================
# Acutator -log Info
# ===============================
management:
 endpoints:
  web:
   base-path: /sysAdmin
   exposure:
    include: health,info,logfile,beans,heapdump
 endpoint:
  gateway:
   enabled: true
  health:
   show-details: always
