server:
 port: 9013
 servlet:
  context-path: /Account

spring:
 application:
  name: account-service
 profiles:
  active: dev
#================================
# Allow Cross-Origins
#================================  
ui:
 cross:
  url: "*"
